# Generated by Django 4.1 on 2022-09-12 22:54

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emisor', models.EmailField(max_length=254)),
                ('remitente', models.EmailField(max_length=254)),
                ('cuerpo', ckeditor.fields.RichTextField()),
                ('leido', models.BooleanField()),
            ],
        ),
    ]
