# Generated by Django 4.1 on 2022-09-12 22:54

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=40)),
                ('subtitulo', models.CharField(max_length=60)),
                ('autor', models.EmailField(max_length=254)),
                ('fecha', models.DateField()),
                ('cuerpo', ckeditor.fields.RichTextField()),
                ('imangen', models.ImageField(upload_to='')),
                ('likes', models.BooleanField()),
            ],
        ),
    ]
